kind: ConfigMap
apiVersion: v1
metadata:
  name: bigbang-k3d-dev-values
  namespace: bigbang
stringData:
  etchost: |
    {{- range $alias := .Values.k3d.hostAliases }}
    {{ $alias.ip }} {{- range $hostname := $alias.hostnames }} {{ $hostname }} {{- end -}}
    {{- end }}
  values.yaml: |
    {{- $generatedValues := dict "istioGateway" (dict "values" (dict "gateways" (dict "public" (dict "upstream" (dict "service" (dict "loadBalancerIP" .Values.k3d.hostAliases.public.ip))) "passthrough" (dict "upstream" (dict "service" (dict "loadBalancerIP" .Values.k3d.hostAliases.passthrough.ip)))))) }}
    {{- $devValues := mergeOverwrite (deepCopy $generatedValues) (.Values.overrides | default dict) }}
{{ toYaml $devValues | nindent 4 }}
